//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flakesnow.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reminder")]
        public string Reminder1Title {
            get {
                return ((string)(this["Reminder1Title"]));
            }
            set {
                this["Reminder1Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reminder")]
        public string Reminder2Title {
            get {
                return ((string)(this["Reminder2Title"]));
            }
            set {
                this["Reminder2Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reminder")]
        public string Reminder3Title {
            get {
                return ((string)(this["Reminder3Title"]));
            }
            set {
                this["Reminder3Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reminder")]
        public string Reminder4Title {
            get {
                return ((string)(this["Reminder4Title"]));
            }
            set {
                this["Reminder4Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reminder")]
        public string Reminder5Title {
            get {
                return ((string)(this["Reminder5Title"]));
            }
            set {
                this["Reminder5Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reminder")]
        public string Reminder6Title {
            get {
                return ((string)(this["Reminder6Title"]));
            }
            set {
                this["Reminder6Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Type here...")]
        public string Reminder1Text {
            get {
                return ((string)(this["Reminder1Text"]));
            }
            set {
                this["Reminder1Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Type here...")]
        public string Reminder2Text {
            get {
                return ((string)(this["Reminder2Text"]));
            }
            set {
                this["Reminder2Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Type here...")]
        public string Reminder3Text {
            get {
                return ((string)(this["Reminder3Text"]));
            }
            set {
                this["Reminder3Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Type here...")]
        public string Reminder4Text {
            get {
                return ((string)(this["Reminder4Text"]));
            }
            set {
                this["Reminder4Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Type here...")]
        public string Reminder5Text {
            get {
                return ((string)(this["Reminder5Text"]));
            }
            set {
                this["Reminder5Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Type here...")]
        public string Reminder6Text {
            get {
                return ((string)(this["Reminder6Text"]));
            }
            set {
                this["Reminder6Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Reminder1Active {
            get {
                return ((bool)(this["Reminder1Active"]));
            }
            set {
                this["Reminder1Active"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Reminder2Active {
            get {
                return ((bool)(this["Reminder2Active"]));
            }
            set {
                this["Reminder2Active"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Reminder3Active {
            get {
                return ((bool)(this["Reminder3Active"]));
            }
            set {
                this["Reminder3Active"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Reminder4Active {
            get {
                return ((bool)(this["Reminder4Active"]));
            }
            set {
                this["Reminder4Active"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Reminder5Active {
            get {
                return ((bool)(this["Reminder5Active"]));
            }
            set {
                this["Reminder5Active"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Reminder6Active {
            get {
                return ((bool)(this["Reminder6Active"]));
            }
            set {
                this["Reminder6Active"] = value;
            }
        }
    }
}
